import type { LucideIcon } from "lucide-react";
import {
  Briefcase,
  Bug,
  Building2,
  Camera,
  Circle,
  Cloud,
  Code,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Droplets,
  Flame,
  Globe,
  Headphones,
  Heart,
  Hexagon,
  Image,
  Key,
  Landmark,
  Leaf,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Mic,
  Moon,
  Music,
  Phone,
  Radio,
  Receipt,
  Rocket,
  Send,
  Server,
  Settings,
  Shield,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  Terminal,
  Triangle,
  Video,
  Wrench,
  Zap,
} from "lucide-react";

export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  MessageSquare,
  Mail,
  Phone,
  Send,
  Megaphone,
  Radio,
  Briefcase,
  Building2,
  Store,
  Landmark,
  CreditCard,
  Receipt,
  Server,
  Database,
  Cloud,
  Code,
  Terminal,
  Cpu,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Rocket,
  Zap,
  Star,
  Heart,
  Globe,
  Compass,
  Leaf,
  Sun,
  Moon,
  Flame,
  Snowflake,
  Droplets,
  Wrench,
  Settings,
  Shield,
  Lock,
  Key,
  Bug,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Diamond,
  Sparkles,
};

export const LUCIDE_ICONS: Record<string, string[]> = {
  Comunicação: ["MessageSquare", "Mail", "Phone", "Send", "Megaphone", "Radio"],
  Negócios: ["Briefcase", "Building2", "Store", "Landmark", "CreditCard", "Receipt"],
  Tecnologia: ["Server", "Database", "Cloud", "Code", "Terminal", "Cpu"],
  Mídia: ["Camera", "Image", "Video", "Music", "Headphones", "Mic"],
  Objetos: ["Rocket", "Zap", "Star", "Heart", "Globe", "Compass"],
  Natureza: ["Leaf", "Sun", "Moon", "Flame", "Snowflake", "Droplets"],
  Ferramentas: ["Wrench", "Settings", "Shield", "Lock", "Key", "Bug"],
  Formas: ["Circle", "Square", "Triangle", "Hexagon", "Diamond", "Sparkles"],
};

export const EMOJI_GRID: Record<string, string[]> = {
  Rostos: [
    "😀",
    "😊",
    "😎",
    "🤩",
    "😂",
    "🥳",
    "😇",
    "🤔",
    "😴",
    "🫡",
    "🤖",
    "👻",
    "💀",
    "🎃",
    "😈",
    "👽",
  ],
  Gestos: [
    "👋",
    "👍",
    "👎",
    "✌️",
    "🤞",
    "🤙",
    "👏",
    "🙌",
    "💪",
    "🫶",
    "🤝",
    "✊",
    "🖐️",
    "👆",
    "👇",
    "🫵",
  ],
  Objetos: [
    "🚀",
    "⚡",
    "🔥",
    "💎",
    "🎯",
    "🏆",
    "🎨",
    "🔔",
    "📦",
    "🎁",
    "🔑",
    "💡",
    "📌",
    "📊",
    "💻",
    "📱",
  ],
  Natureza: [
    "🌟",
    "⭐",
    "🌈",
    "🌙",
    "☀️",
    "🌊",
    "🍀",
    "🌸",
    "🌺",
    "🌻",
    "🌴",
    "🍄",
    "🦋",
    "🐱",
    "🐶",
    "🦄",
  ],
  Símbolos: [
    "✅",
    "❌",
    "❤️",
    "💜",
    "💙",
    "💚",
    "💛",
    "🧡",
    "🤍",
    "🖤",
    "♻️",
    "⚙️",
    "🔗",
    "📍",
    "🏁",
    "💬",
  ],
};

export interface ColorSwatch {
  label: string;
  value: string;
}

export const COLOR_SWATCHES: ColorSwatch[] = [
  { label: "Slate", value: "#64748b" },
  { label: "Red", value: "#ef4444" },
  { label: "Orange", value: "#f97316" },
  { label: "Amber", value: "#f59e0b" },
  { label: "Lime", value: "#84cc16" },
  { label: "Green", value: "#22c55e" },
  { label: "Emerald", value: "#10b981" },
  { label: "Teal", value: "#14b8a6" },
  { label: "Cyan", value: "#06b6d4" },
  { label: "Sky", value: "#0ea5e9" },
  { label: "Blue", value: "#3b82f6" },
  { label: "Indigo", value: "#6366f1" },
  { label: "Violet", value: "#8b5cf6" },
  { label: "Purple", value: "#a855f7" },
  { label: "Fuchsia", value: "#d946ef" },
  { label: "Pink", value: "#ec4899" },
  { label: "Rose", value: "#f43f5e" },
];
